version: '3'

services:

  mongo:
    image: mongo:latest
    volumes:
      - .tockmongo:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles --bind_ip_all
    
  build_worker:
    image: tock/build_worker:$TAG
    depends_on:
      - mongo
    environment:
      - tock_mongo_url=mongodb://mongo:27017
      - tock_env=prod

  duckling:
    image: tock/duckling:$TAG
    environment:
      - tock_env=prod
    expose:
      - "8080"

  kotlin_compiler:
    image: tock/kotlin_compiler:$TAG
    environment:
      - tock_env=prod
      - tock_kotlin_compiler_classpath=/maven
    expose:
      - "8080"

  admin_web:
    image: tock/bot_admin:$TAG
    depends_on:
      - mongo
      - duckling
      - kotlin_compiler
    environment:
      - tock_mongo_url=mongodb://mongo:27017
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_bot_admin_rest_default_base_url=http://bot_open_data:8080
      - tock_bot_compiler_service_url=http://kotlin_compiler:8080
    ports:
      - "80:8080"

  nlp_api:
    image: tock/nlp_api:$TAG
    depends_on:
      - mongo
      - duckling
    environment:
      - tock_mongo_url=mongodb://mongo:27017
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_web_use_default_cors_handler=true
      - tock_web_use_default_cors_handler_with_credentials=false
      - tock_web_use_default_cors_handler_url=*
    ports:
      - "8888:8080"

