version: '3'

services:

  mongo:
    image: mongo:latest
    volumes:
      - .tockmongo:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles --rest

  duckling:
      image: tock/duckling:$TAG
      environment:
        - tock_mongo_url=mongodb://mongo:27017
        - tock_env=prod
      ports:
        - "8889:8080"