version: '3'

services:

  mongo:
    image: mongo:latest
    volumes:
      - .tockmongo:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles --bind_ip_all --port 27017 --replSet "tock"

  mongo2:
    image: mongo:latest
    depends_on:
      - mongo
    volumes:
      - .tockmongo2:/data/db
    ports:
      - "27018:27017"
    command: --smallfiles --bind_ip_all --port 27017 --replSet "tock"

  mongo3:
    image: mongo:latest
    depends_on:
      - mongo
      - mongo2
    volumes:
      - .tockmongo3:/data/db
    ports:
      - "27019:27017"
    command: --smallfiles --bind_ip_all --port 27017 --replSet "tock"

  mongo-setup:
    container_name: "mongo-setup"
    image: mongo
    depends_on:
      - "mongo"
      - "mongo2"
      - "mongo3"
    links:
      - mongo:mongo
      - mongo2:mongo2
      - mongo3:mongo3
    volumes:
      - ./scripts:/scripts
    environment:
      - MONGO1=mongo
      - MONGO2=mongo2
      - MONGO3=mongo3
      - RS=tock
    entrypoint: [ "/scripts/setup.sh" ]
    
  build_worker:
    image: tock/build_worker:$TAG
    depends_on:
      - mongo
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27017,mongo3:27017/?replicaSet=tock
      - tock_env=prod

  duckling:
    image: tock/duckling:$TAG
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27017,mongo3:27017/?replicaSet=tock
      - tock_env=prod
    expose:
      - "8080"

  admin_web:
    image: tock/nlp_admin:$TAG
    depends_on:
      - mongo
      - duckling
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27017,mongo3:27017/?replicaSet=tock
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
    ports:
      - "80:8080"

  nlp_api:
    image: tock/nlp_api:$TAG
    depends_on:
      - mongo
      - duckling
    environment:
      - tock_mongo_url=mongodb://mongo:27017,mongo2:27017,mongo3:27017/?replicaSet=tock
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_web_use_default_cors_handler=true
      - tock_web_use_default_cors_handler_with_credentials=false
      - tock_web_use_default_cors_handler_url=*
    ports:
      - "8888:8080"