version: '3'

services:

  mongo:
    image: mongo:latest
    volumes:
      - .tockmongo:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles --bind_ip_all
    
  build_worker:
    image: tock/build_worker:$TAG
    depends_on:
      - mongo
    environment:
      - tock_mongo_url=mongodb://mongo:27017
      - tock_env=prod

  duckling:
    image: tock/duckling:$TAG
    environment:
      - tock_mongo_url=mongodb://mongo:27017
      - tock_env=prod
    expose:
      - "8080"

  admin_web:
    image: tock/nlp_admin:$TAG
    depends_on:
      - mongo
      - duckling
    environment:
      - tock_mongo_url=mongodb://mongo:27017
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
    ports:
      - "80:8080"

  nlp_api:
    image: tock/nlp_api:$TAG
    depends_on:
      - mongo
      - duckling
    environment:
      - tock_mongo_url=mongodb://mongo:27017
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
    ports:
      - "8888:8080"